### ISSUE TITLE
Crashes on seth send

### ISSUE THREAD

**Issue by ranveerkunal** [dapphub/seth#14]
seth send -F <ETH_ADDRESS> -G 4600000 --value=$(seth --to-wei <CONTRIBUTION> ETH) <CONTRACT_ADDRESS> "buy()"

/nix/store/s3dr5125qxipb8npn4wk544lszvkcb5p-seth-0.5.6/libexec/seth/seth---decorate-abi:3
var { execFileSync } = require("child_process")
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by ranveerkunal** [comment]
I am putting the correct ETH/CONTRACT address of course.

**Comment by dbrock** [comment]
Oops, I guess you need a newer version of Node.js.

**Comment by ranveerkunal** [comment]
Will try thanks.
